services:
  mysql:
    image: mysql:latest
    container_name: bilster
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadminbilster
    restart: always
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: qwerty
    ports:
      - "8080:80"

  